# Generated by Django 4.1.7 on 2023-04-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
        migrations.AddField(
            model_name='sellers',
            name='acc_num',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellers',
            name='bank',
            field=models.CharField(default='aaaa', max_length=100),
            preserve_default=False,
        ),
    ]
