# Generated by Django 4.1.7 on 2023-04-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_buyers_sellers_acc_num_sellers_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='amount_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellers',
            name='average_product_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellers',
            name='no_of_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellers',
            name='no_of_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellers',
            name='pending_orders',
            field=models.IntegerField(default=0),
        ),
    ]
