# Generated by Django 4.1.7 on 2023-04-11 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_sellers_amount_earned_sellers_average_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('acc_num', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=100)),
                ('amount_earned', models.IntegerField(default=0)),
                ('no_of_sales', models.IntegerField(default=0)),
                ('no_of_products', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('average_product_rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
