# Generated by Django 4.1.7 on 2023-04-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seller_delete_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default='aaa', max_length=12),
            preserve_default=False,
        ),
    ]
