# Generated by Django 4.1.7 on 2023-04-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='acc_name',
            field=models.CharField(default='Bayode Iretomiwa', max_length=100),
            preserve_default=False,
        ),
    ]
