# Generated by Django 4.1.7 on 2023-04-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seller_acc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
