# Generated by Django 4.1.7 on 2023-04-11 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=100)),
                ('picture1', models.ImageField(default='cart.png', upload_to='pics')),
                ('picture2', models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics')),
                ('picture3', models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics')),
                ('picture4', models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics')),
                ('picture5', models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics')),
                ('seller', models.CharField(max_length=150)),
                ('seller_email', models.EmailField(max_length=100)),
                ('seller_telegram_number', models.CharField(max_length=12)),
                ('seller_whatsapp_number', models.CharField(max_length=12)),
                ('seller_instagram', models.CharField(max_length=12)),
                ('type', models.CharField(choices=[('food', 'FOOD'), ('fashion', 'FASHION'), ('gadgets', 'GADGETS'), ('school', 'SCHOOL'), ('cosmetics', 'COSMETICS'), ('miscellaneous', 'MISCELLANEOUS')], default='miscellaneous', max_length=20)),
                ('sales', models.IntegerField(default=0)),
                ('details', models.TextField()),
                ('rating', models.IntegerField(default=3)),
                ('arating', models.DecimalField(decimal_places=1, default=3, max_digits=2)),
                ('amount', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
