# Generated by Django 4.1.7 on 2023-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
