# Generated by Django 4.1.7 on 2023-04-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_type_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='instagram',
            field=models.CharField(default='ded.sec10', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, default='1160358.png', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, default='1160358.png', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture4',
            field=models.ImageField(blank=True, default='1160358.png', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture5',
            field=models.ImageField(blank=True, default='1160358.png', null=True, upload_to='pics'),
        ),
    ]
