# Generated by Django 4.1.7 on 2023-04-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seller_instagram_alter_product_picture2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_telegram_number',
            new_name='seller_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_whatsapp_number',
        ),
    ]
