# Generated by Django 4.1.7 on 2023-04-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_seller_telegram_number_product_seller_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='quantity',
        ),
    ]
