# Generated by Django 4.1.7 on 2023-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_amount_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=100),
            preserve_default=False,
        ),
    ]
