# Generated by Django 4.1.7 on 2023-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
