# Generated by Django 4.1.7 on 2023-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='do_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
