# Generated by Django 4.1.7 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_do_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_instagram',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
