# Generated by Django 4.1.7 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_details_alter_product_seller_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='do_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
