# Generated by Django 4.1.7 on 2023-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_do_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='average_product_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
