# Generated by Django 4.1.7 on 2023-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_seller_average_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='telegram',
            field=models.CharField(default='09055573607', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='whatsapp',
            field=models.CharField(default='09055573607', max_length=12),
            preserve_default=False,
        ),
    ]
