# Generated by Django 4.1.7 on 2023-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seller_telegram_seller_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
