# Generated by Django 4.1.7 on 2023-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_arating_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
            ],
        ),
    ]
