# Generated by Django 4.1.7 on 2023-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_review_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
